module Rubac
  class Checker
    @tuples: Array[Rubac::Tuple]
    def check?: -> bool

    private

    def direct_object_matches: (TupleKey) -> Array[Tuple]

    def related_object_matches: (String, Array[Tuple]?) -> Array[Tuple]

    def rewrite_usersets: (Array[Tuple]) -> void

  end
end
