module Rubac
  class TupleKey

    attr_accessor object: String
    attr_accessor relation: String

    attr_accessor user: String

    def object_type: -> String

    def user_type: -> String
  end
end
