module Rubac
  class User
    @type: String?
    @id: String?
    @relation: String?

    attr_reader id: String?
    attr_reader relation: String?
    attr_reader type: String?

    def is: -> bool

    def is_userset: -> bool

    def is_wildcard: -> bool

    def qualified_id: -> String
  end
end
